"""add_submitted_by_to_report_status

Revision ID: 21559dd8427b
Revises: f8a6aaf92b49
Create Date: 2026-05-08 22:15:45.197190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21559dd8427b'
down_revision: Union[str, None] = 'f8a6aaf92b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_statuses', sa.Column('submitted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report_statuses', 'users', ['submitted_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_statuses', type_='foreignkey')
    op.drop_column('report_statuses', 'submitted_by_id')
    # ### end Alembic commands ###
