"""initial

Revision ID: c24615847530
Revises: 
Create Date: 2026-05-07 19:26:58.681270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c24615847530'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
