"""add_feedback_to_report_file

Revision ID: f8a6aaf92b49
Revises: 0b59a480720f
Create Date: 2026-05-08 22:03:17.504668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8a6aaf92b49'
down_revision: Union[str, None] = '0b59a480720f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_files', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_files', 'feedback')
    # ### end Alembic commands ###
